Repository babybuddy/babybuddy, pull requests merged in 2022-05, with the labels that each got.

#443 Allow end of feeding to be in the future
  core/models.py
Labels: enhancement

#452 fix typo
  docs/setup/proxy.md
Labels: documentation

#445 Fix KeyError at /children/x/reports/sleep/pattern/
  reports/graphs/sleep_pattern.py
Labels: bug

#450 Add carousel of last 7 days of feedings to the todays feeding card
  api/tests.py
  babybuddy/fixtures/tests.json
  core/templatetags/duration.py
  core/tests/tests_templatetags.py
  dashboard/templates/cards/feeding_day.html
  dashboard/templatetags/cards.py
  dashboard/tests/tests_templatetags.py
Labels: enhancement
