Repository babybuddy/babybuddy, pull requests merged in 2024-08, with the labels that each got.

#869 Update django.po
  locale/nl/LC_MESSAGES/django.mo
  locale/nl/LC_MESSAGES/django.po
Labels: bug, i18n/L10n

#861 Allow pumping sessions to be timed via API
  api/serializers.py
  api/tests.py
Labels: enhancement

#873 fix: Ensure child ID is included in exports
  core/admin.py
Labels: bug
